services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - devohh-network
    volumes:
      - zookeeper-data:/var/lib/zookeeper

  kafka:
    image: quay.io/debezium/kafka:3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - devohh-network
    volumes:
      - kafka-data:/var/lib/kafka/data

  connect:
    image: quay.io/debezium/connect:3.2
    container_name: connect
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    networks:
      - devohh-network
    volumes:
      - connect-data:/kafka/connect

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    command: postgres -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contests_db
    networks:
      - devohh-network
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - devohh-network

volumes:
  db-data:
  # rabbitmq-data:
  zookeeper-data:
  kafka-data:
  connect-data:
  redis-data:

networks:
  devohh-network:
    external: true