version: "3.8"

services:
  problems-api:
    build:
      context: ../app/problems
      dockerfile: Dockerfile
    container_name: problems-api
    environment:
      - NODE_ENV=development
      - PROBLEMS_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/problems_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    command: pnpm run start:api
    ports:
      - "3000:3000"
    networks:
      - devohh-network

  # problems-worker:
  #   build:
  #     context: ../app/problems
  #     dockerfile: Dockerfile
  #   container_name: problems-worker
  #   privileged: true
  #   environment:
  #     - NODE_ENV=development
  #     - PROBLEMS_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/problems_db
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
  #   command: sh -c "dockerd-entrypoint.sh & sleep 5 && pnpm run start:worker"
  #   ports:
  #     - "4000:4000"
  #   networks:
  #     - devohh-network

  # discussions-api:
  #   build:
  #     context: ../app/discussions
  #     dockerfile: Dockerfile
  #   container_name: discussions-api
  #   environment:
  #     - NODE_ENV=development
  #     - DISCUSSIONS_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/discussions_db
  #   command: pnpm run start:api
  #   ports:
  #     - "3001:3001"
  #   networks:
  #     - devohh-network

  contests-api:
    build:
      context: ../app/contests
      dockerfile: Dockerfile
    container_name: contests-api
    environment:
      - NODE_ENV=development
      - CONTESTS_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/contests_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - PROBLEM_SERVICE_URL=http://problems-api:3000
    command: pnpm run start:api
    ports:
      - "3002:3002"
    networks:
      - devohh-network

  contests-worker:
    build:
      context: ../app/contests
      dockerfile: Dockerfile
    container_name: contests-worker
    privileged: true
    environment:
      - NODE_ENV=development
      - CONTESTS_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/contests_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    command: sh -c "dockerd-entrypoint.sh & sleep 5 && pnpm run start:worker"
    ports:
      - "3010:3010"
    networks:
      - devohh-network

  leaderboards-debezium:
    build:
      context: ../app/leaderboards
      dockerfile: Dockerfile
    container_name: leaderboards-debezium
    environment:
      - NODE_ENV=development
      - KAFKA_BROKER_URL=kafka:9092
      - REDIS_HOST=redis
      - DEBEZIUM_CONNECTOR_URL=http://connect:8083
    command: pnpm run start:debezium
    depends_on:
      - leaderboards-api
    networks:
      - devohh-network

  leaderboards-api:
    build:
      context: ../app/leaderboards
      dockerfile: Dockerfile
    container_name: leaderboards-api
    environment:
      - NODE_ENV=development
      - PORT=3003
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    command: sh -c "pnpm run migrate && pnpm run start"
    networks:
      - devohh-network

networks:
  devohh-network:
    external: true
